[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
insta = "1.41.1"
itertools = "0.13.0"
regex = "1.11.1"
strum = { version = "0.26.3", features = ["derive"] }
