[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"
rust-version = "1.74.1"

[dependencies]
chumsky = "1.0.0-alpha.6"
format = "0.2.4"
insta = "1.34.0"
itertools = "0.12.0"
joinery = "3.1.0"
nutype = "0.4.0"
